### ISSUE TITLE
Cannot scan some TypeScript compiler CJS output

### ISSUE THREAD

**Issue by FredKSchott** [guybedford/cjs-module-lexer#37] opened 2021-03-01 03:04 UTC
/cc @BPScott
https://unpkg.com/@shopify/polaris-tokens@2.20.0/dist-modern/index.js

```
'use strict';
Object.defineProperty(exports, '__esModule', {value: true});
exports.colorFactory = void 0;
var color_factory_1 = require('./color-factory');
Object.defineProperty(exports, 'colorFactory', {
  enumerable: true,
  get: function () {
    return color_factory_1.colorFactory;
  },
});
```

```
{ exports: [ '__esModule' ], reexports: [] }
```

cjs-module-lexer properly scans `__esModule`, but does not scan `colorFactory`. Is this expected? If so, is the presence of `get` instead of `value` also enough to indicate an export?

**Comment by BPScott** [comment] 2021-03-01 03:26
This code was generated from using the Typescript 4.1 compiler, outputting to cjs

The source code was:

```
export {colorFactory} from './color-factory';
```

[Here's a TS  playground demonstrating this output](https://www.typescriptlang.org/play?module=1#code/KYDwDg9gTgLgBAbwMYQDbQGIEMk2gTwF84AzKCAWzgHIA6AehXSgFoSc8p9qBuIA)

**Comment by BPScott** [comment] 2021-03-01 03:52
Looks like TS changed its output in TS 3.9.x. Contrast [3.8 output](https://www.typescriptlang.org/play?module=1&ts=3.8.3#code/KYDwDg9gTgLgBAbwMYQDbQGIEMk2gTwF84AzKCAWzgHIA6AehXSgFoSc8p9qBuIA) vs [3.9 output](https://www.typescriptlang.org/play?module=1&ts=3.9.7#code/KYDwDg9gTgLgBAbwMYQDbQGIEMk2gTwF84AzKCAWzgHIA6AehXSgFoSc8p9qBuIA)

**Comment by guybedford** [comment] 2021-03-07 10:25
Turns out this is a duplicate of https://github.com/guybedford/cjs-module-lexer/issues/31 and not actually related to the TypeScript output change but the trailing comma added to the property definition.

Will aim to backport the fix on Node.js as far as possible, but bear in mind Node.js 12 support isn't assured at this point.

**Closed** 2021-03-07 10:26 UTC

**Comment by BPScott** [comment] 2021-03-07 21:10
Great hunting. Thank you @guybedford!
